/**
 * Derive/render half of `labs/workbench/scripts/generate-text-compat-tokens.mts`,
 * split out so the drift gate (`text-compat-tokens.test.ts`) runs the
 * generator's own logic instead of a second copy (`css-color-names.ts`
 * precedent). Takes the ui/src/theme values as parameters — importing ui here
 * would hand mycelium a runtime dependency on the package being migrated away
 * from; only the generator and the test (which already imports ui) load them.
 *
 * The TS mirror is compared value-for-value, not byte-for-byte: oxfmt rewraps
 * the rendered module, so bytes are only stable for the CSS file.
 */

export const TEXT_COMPAT_HEADER = `Generated by labs/workbench/scripts/generate-text-compat-tokens.mts — do not edit.
Mirrors ui/src/theme (themes.ts + fonts.ts + tamaguiFonts.ts, web values); the
drift gate is packages/mycelium/src/scripts/text-compat-tokens.test.ts and the
computed-style harness labs/workbench/scripts/verify-text-parity.mts proves the
mirrored values correct.`

export type FontFamilyKey = 'book' | 'medium' | 'mono'

export interface DerivedVariantMetrics {
  fontSize: number
  lineHeight: number
  fontWeight: number
  family: FontFamilyKey
}

export interface DerivedFontDefinition {
  family: FontFamilyKey
  sizes: Record<string, number>
  lineHeights: Record<string, number>
}

/** The shape of a `ui/src/theme/fonts.ts` variant entry this derivation reads. */
export interface UiFontVariant {
  fontSize: number
  lineHeight: number
  fontWeight?: string
}

/** The shape of a `ui/src/theme/tamaguiFonts.ts` font entry this derivation reads. */
export interface UiTamaguiFont {
  size: Record<string, unknown>
  lineHeight?: Record<string, unknown>
}

/** Theme color token names, sorted — the members of the --stext-* mirror. */
export function deriveThemeColorTokens(lightTheme: Record<string, string>): string[] {
  const names = Object.keys(lightTheme).sort()
  if (names.length === 0) {
    throw new Error('deriveThemeColorTokens: ui themes.light has zero tokens — refusing to render an empty mirror')
  }
  return names
}

/**
 * Font stack per variant, from Text.tsx's variant definitions:
 * headings/subheadings/body use the heading/subHeading/body fonts (Basel book
 * stack), buttonLabel* uses the button font (Basel medium stack — same stack
 * on web), monospace uses the monospace font.
 */
function familyKey(variantName: string): FontFamilyKey {
  if (variantName === 'monospace') {
    return 'mono'
  }
  return variantName.startsWith('buttonLabel') ? 'medium' : 'book'
}

// Web app font weights (fonts.ts defaultWeights with isWebApp): book 485, medium 535.
const WEB_WEIGHT: Record<string, number> = { '400': 485, '500': 535 }

const round = (value: number): number => Math.round(value * 100) / 100

/** The legacy web type scale per Text variant (fonts.ts web values, app weights 485/535). */
export function deriveVariantMetrics(fonts: Record<string, UiFontVariant>): Record<string, DerivedVariantMetrics> {
  const out: Record<string, DerivedVariantMetrics> = {}
  for (const [name, entry] of Object.entries(fonts)) {
    const weight = entry.fontWeight !== undefined ? WEB_WEIGHT[entry.fontWeight] : 485
    if (weight === undefined) {
      throw new Error(`Unmapped web font weight for variant ${name}`)
    }
    out[name] = {
      fontSize: round(entry.fontSize),
      lineHeight: round(entry.lineHeight),
      fontWeight: weight,
      family: familyKey(name),
    }
  }
  if (Object.keys(out).length === 0) {
    throw new Error('deriveVariantMetrics: ui fonts has zero variants')
  }
  return out
}

const FONT_FAMILY_KEY: Record<string, FontFamilyKey> = {
  heading: 'book',
  subHeading: 'book',
  body: 'book',
  button: 'medium',
  monospace: 'mono',
}

/** The Tamagui font tokens: per-font size/lineHeight token maps, resolved to px. */
export function deriveFontDefinitions(allFonts: Record<string, UiTamaguiFont>): Record<string, DerivedFontDefinition> {
  const out: Record<string, DerivedFontDefinition> = {}
  for (const [name, font] of Object.entries(allFonts)) {
    const family = FONT_FAMILY_KEY[name]
    if (family === undefined) {
      throw new Error(`Unmapped font token ${name}`)
    }
    const numericMap = (map: Record<string, unknown>): Record<string, number> =>
      Object.fromEntries(
        Object.entries(map).map(([key, value]) => {
          const numeric = round(Number(value))
          // Number(value) silently produces NaN for anything non-numeric —
          // the adjacent unmapped-weight/unmapped-token paths in this file
          // throw on bad input instead of propagating it, and a literal NaN
          // written into the rendered mirror would be the same silent-drift
          // failure mode this generator otherwise refuses everywhere else.
          if (Number.isNaN(numeric)) {
            throw new Error(`deriveFontDefinitions: non-numeric value for token "${name}.${key}": ${String(value)}`)
          }
          return [key, numeric]
        }),
      )
    out[name] = {
      family,
      sizes: numericMap(font.size),
      lineHeights: numericMap(font.lineHeight ?? {}),
    }
  }
  if (Object.keys(out).length === 0) {
    throw new Error('deriveFontDefinitions: ui allFonts has zero fonts')
  }
  return out
}

/**
 * Token names with the dark-twin invariant enforced. ui/src/theme's BaseTheme
 * type (themes.ts) structurally requires `dark` to declare exactly the same
 * keys as `light`, so every light token is expected to have a dark twin. A
 * silent gap would render `--stext-<name>: undefined;` — an invalid
 * declaration that falls back to the light value in dark mode with no signal
 * anything went wrong — so refuse it loudly instead, matching the
 * throw-on-bad-input discipline the rest of this file already follows.
 */
function deriveThemedTokenNames(
  lightTheme: Record<string, string>,
  darkTheme: Record<string, string>,
  callerLabel: string,
): string[] {
  const tokenNames = deriveThemeColorTokens(lightTheme)
  const missingDarkTwin = tokenNames.filter((name) => !(name in darkTheme))
  if (missingDarkTwin.length > 0) {
    throw new Error(
      `${callerLabel}: theme token(s) present in light but missing from dark: ${missingDarkTwin.join(', ')}`,
    )
  }
  return tokenNames
}

/** Wraps a header comment block the same way for both the web and native CSS renderers. */
function renderHeaderComment(header: string): string {
  return `/* ${header.split('\n').join('\n * ')} */`
}

/** The --stext-* palette stylesheet, byte-stable (never formatted by oxfmt). */
export function renderSporeTextColorsCss(
  lightTheme: Record<string, string>,
  darkTheme: Record<string, string>,
): string {
  const tokenNames = deriveThemedTokenNames(lightTheme, darkTheme, 'renderSporeTextColorsCss')
  return [
    renderHeaderComment(TEXT_COMPAT_HEADER),
    ':root {',
    ...tokenNames.map((name) => `  --stext-${name}: ${lightTheme[name]};`),
    '}',
    '',
    '.dark {',
    ...tokenNames
      .filter((name) => darkTheme[name] !== lightTheme[name])
      .map((name) => `  --stext-${name}: ${darkTheme[name]};`),
    '}',
    '',
  ].join('\n')
}

export const TEXT_COMPAT_NATIVE_HEADER = `${TEXT_COMPAT_HEADER}
Native (uniwind) dialect twin of spore-text-colors.generated.css: uniwind's
native compiler routes \`.dark { … }\` into a CLASS entry, not the dark theme
bucket, so the web file's dark overrides never reach Uniwind.setTheme(). This
twin declares the SAME values in uniwind's theme dialect (\`@layer theme {
:root { @variant light|dark { … } } }\`) — both buckets declare the full key
set because uniwind resolves a partial override to undefined. The
--stext-font-* stacks stay web-only on purpose (native weights come from font
FILES; see text-compat/native-style.ts). Value lockstep with the web file is
pinned by packages/tailwind/src/parity/native-bundle/native-parity.test.ts.`

/**
 * The native-dialect twin of the --stext-* palette, byte-stable. Unlike the
 * web file's \`.dark\` override block, both buckets carry the FULL key set:
 * uniwind resolves a key missing from one theme bucket to undefined rather
 * than falling back to the other bucket's value.
 */
export function renderSporeTextColorsNativeCss(
  lightTheme: Record<string, string>,
  darkTheme: Record<string, string>,
): string {
  const tokenNames = deriveThemedTokenNames(lightTheme, darkTheme, 'renderSporeTextColorsNativeCss')
  return [
    renderHeaderComment(TEXT_COMPAT_NATIVE_HEADER),
    '@layer theme {',
    '  :root {',
    '    @variant light {',
    ...tokenNames.map((name) => `      --stext-${name}: ${lightTheme[name]};`),
    '    }',
    '    @variant dark {',
    ...tokenNames.map((name) => `      --stext-${name}: ${darkTheme[name]};`),
    '    }',
    '  }',
    '}',
    '',
  ].join('\n')
}

/** The theme-tokens TS mirror module (oxfmt may rewrap it after writing). */
export function renderThemeTokensModule(args: {
  tokenNames: readonly string[]
  variantMetrics: Record<string, DerivedVariantMetrics>
  fontDefinitions: Record<string, DerivedFontDefinition>
}): string {
  const variantEntries = Object.entries(args.variantMetrics).map(
    ([name, m]) =>
      `  ${name}: { fontSize: ${m.fontSize}, lineHeight: ${m.lineHeight}, fontWeight: ${m.fontWeight}, family: '${m.family}' },`,
  )
  const inlineMap = (map: Record<string, number>): string =>
    Object.entries(map)
      .map(([key, value]) => `${key}: ${value}`)
      .join(', ')
  const fontDefinitionEntries = Object.entries(args.fontDefinitions).map(
    ([name, font]) =>
      `  ${name}: { family: '${font.family}', sizes: { ${inlineMap(font.sizes)} }, lineHeights: { ${inlineMap(font.lineHeights)} } },`,
  )

  return `/**
 * ${TEXT_COMPAT_HEADER.split('\n').join('\n * ')}
 */

/** Every theme color token the legacy Text \`color\` prop accepts, as --stext-* CSS vars. */
export const THEME_COLOR_TOKENS = [
${args.tokenNames.map((name) => `  '${name}',`).join('\n')}
] as const

export type ThemeColorToken = (typeof THEME_COLOR_TOKENS)[number]

export interface VariantMetrics {
  fontSize: number
  lineHeight: number
  fontWeight: number
  family: 'book' | 'medium' | 'mono'
}

/** The legacy web type scale per Text variant (fonts.ts web values, app weights 485/535). */
export const VARIANT_METRICS = {
${variantEntries.join('\n')}
} as const

export type TextVariant = keyof typeof VARIANT_METRICS

export interface FontDefinition {
  family: 'book' | 'medium' | 'mono'
  /** Font-relative fontSize tokens ($small, $large, …) → px. */
  sizes: Readonly<Record<string, number>>
  /** Font-relative lineHeight tokens → px. */
  lineHeights: Readonly<Record<string, number>>
}

/**
 * The Tamagui font tokens ($heading/$subHeading/$body/$button/$monospace):
 * fontSize/lineHeight tokens resolve against the active font's own maps.
 */
export const FONT_DEFINITIONS: Readonly<Record<string, FontDefinition>> = {
${fontDefinitionEntries.join('\n')}
} as const
`
}
