/**
 * The full generated compat class manifest (INFRA-3217): the base-tier
 * family vocabulary, the var-indirection twin matrix (utility-twin ×
 * variant-prefix), and every component's fixed-frame contribution. This
 * module imports every compat compile module AND the enumeration module, so
 * it is only consumed by the generator script and the test gates — the
 * runtime strict path reads the generated membership list
 * (`closed-set-runtime.ts`) and the rendering component's own fixed provider
 * without loading any of this.
 */
import { filterSelectFixedCompatClasses } from '../filter-select-compat/compile'
import { flexFixedCompatClasses } from '../flex-compat/compile'
import { menuFixedCompatClasses } from '../menu-compat/compile'
import { optionListFixedCompatClasses } from '../option-list-compat/compile'
import { popoverFixedCompatClasses } from '../popover-compat/compile'
import { scrollViewFixedCompatClasses } from '../scroll-view-compat/compile'
import { textFixedCompatClasses } from '../text-compat/compile'
import { tooltipFixedCompatClasses } from '../tooltip-compat/compile'
import { touchableAreaFixedCompatClasses } from '../touchable-area/compile'
import { touchableTextLinkFixedCompatClasses } from '../touchable-text-link/compile'
import { compatFamilyClassEntries, compatTwinClassEntries } from './closed-set'
import { collectCompatClassNames } from './closed-set-runtime'

/** Every fixed-frame class contributed by the compat components, split and deduped. */
export function compatFixedClassEntries(): string[] {
  const set = new Set<string>()
  const contributions: readonly string[][] = [
    flexFixedCompatClasses(),
    textFixedCompatClasses(),
    [...touchableAreaFixedCompatClasses()],
    [...touchableTextLinkFixedCompatClasses()],
    [...tooltipFixedCompatClasses()],
    [...popoverFixedCompatClasses()],
    menuFixedCompatClasses(),
    optionListFixedCompatClasses(),
    filterSelectFixedCompatClasses(),
    scrollViewFixedCompatClasses(),
  ]
  for (const classNames of contributions) {
    for (const cls of collectCompatClassNames(classNames)) {
      set.add(cls)
    }
  }
  return [...set]
}

/** Every class of the closed compat set, sorted and unique — the gen.txt contents. */
export function compatClosedSetEntries(): string[] {
  const set = new Set<string>([
    ...compatFamilyClassEntries(),
    ...compatTwinClassEntries(),
    ...compatFixedClassEntries(),
  ])
  // Plain lexicographic sort: deterministic across platforms/locales.
  return [...set].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
}

const GENERATED_HEADER = [
  '/* GENERATED by `bun nx run @universe/mycelium:generate:compat-classes` — do not edit. */',
  '/* The closed compat class set (INFRA-3217): every Tailwind candidate the compat compilers may emit. */',
  '/* Registered via @source from packages/mycelium/tailwind.css; drift-gated by closed-set.test.ts. */',
]

/** The exact bytes of `packages/mycelium/compat-classes.gen.txt`, from precomputed entries. */
export function compatClassesFileContents(entries: readonly string[] = compatClosedSetEntries()): string {
  return [...GENERATED_HEADER, ...entries, ''].join('\n')
}

/** Scanner-proof encoding for generated class literals (see `emitted-classes.ts` for the decoder's twin). */
function encodeScannerProof(cls: string): string {
  return cls.replace(/\[/g, '⟦').replace(/\]/g, '⟧').replace(/:/g, '¦')
}

/**
 * The exact bytes of `src/compat/family-classes.generated.ts` — the runtime
 * membership list. A generated literal (not a runtime enumeration) so the
 * browser neither re-derives the vocabulary nor ships the enumeration module.
 *
 * ENTRIES ARE SCANNER-PROOF-ENCODED (decoded at module init): this file lives
 * inside trees that Tailwind's oxide scanner (apps/web) and uniwind's Metro
 * scanner (apps/mobile) treat as candidate sources. Plain literals here would
 * (a) double-source every family class on web and (b) compile ~950 candidate
 * rules into the MOBILE JS bundle — measured +264 KB on `main.jsbundle`, which
 * is what broke `check:bundlesize` when this file first shipped un-encoded.
 */
export function familyClassesFileContents(): string {
  const entries = compatFamilyClassEntries()
  return [
    '// oxlint-disable max-lines -- generated data file',
    '/* GENERATED by `bun nx run @universe/mycelium:generate:compat-classes` — do not edit. */',
    '/* The base-tier compat family vocabulary (INFRA-3217): the runtime membership list. */',
    '/* Entries are scanner-proof-encoded (⟦ ⟧ ¦ for [ ] :) so no scanner treats this data as candidates. */',
    '/* Drift-gated byte-for-byte by closed-set.test.ts. */',
    'export const ENCODED_COMPAT_FAMILY_CLASSES: readonly string[] = [',
    ...entries.map((cls) => `  '${encodeScannerProof(cls)}',`),
    ']',
    '',
  ].join('\n')
}
